### ISSUE TITLE
[Feature] support boolean values in select_in_values

### ISSUE THREAD

**Issue by iilyak** [ffizer/ffizer#185]
I am trying to render a section conditionally based on a parameter. However it is quite tricky. 

1. Try `using select_in_values`. The following construct silently fails without producing anything.
```
  - name: repo_init
    ask: Do you want to initialize git repository
    default_value: true
    select_in_values:
      - true
      - false
```
2. Try using `{{#if repo_init}}` with strings in `select_in_values`. This doesn't work because `#if` expects boolean:
```
  - name: repo_init
    ask: Do you want to initialize git repository
    default_value: true
    select_in_values:
      - "true"
      - "false"
```
```
{{ #if init }}
git init
git worktree add --track -b gh-pages site origin/gh-pages
{{ /if }}
```
3. Try using `{{#if repo_init}}` with hidden variable. It silently fails because `repo_init` is still a string
```
  - name: ask_repo_init
    ask: Do you want to initialize git repository
    default_value: true
    select_in_values:
      - "true"
      - "false"
  - name: repo_init
    default_value: {{ str_to_json(ask_repo_init) }}
    hidden: true
```
4. assign variable inside template itself. This works but requires boiler plate in every template file.
```
{{ assign "init" (str_to_json(repo_init)) }}
{{ #if init }}
git init
git worktree add --track -b gh-pages site origin/gh-pages
{{ /if }}
```

**Comment by iilyak** [comment]
This also worked
```
{{ #if (str_to_json(repo_init)) }}
git init
git worktree add --track -b gh-pages site origin/gh-pages
{{ /if }}
```

**Comment by davidB** [comment]
Hi,

Thanks for trying ffizer and for reporting this issue.

This is how I did in my template:

```
{{#if (eq  repo_init "true") }}
 ....
{{/if}}
```

But I agree it could be better :

- try to support boolean and other types, without breaking existing templates, for the variables (into the `.ffizer.yaml` and template)
  - for `default_value`
  - for `select_in_values`
  - for input value (maybe template creator will need to request type, `true != "true"` but I don't want to force the user to enclose input in " for string, the most common input (and the only one today ;-))
- provide some how-to in the template authoring doc for common use case

I'll try to work on this suggest asap.

**Comment by iilyak** [comment]
> for input value (maybe template creator will need to request type, true != "true" but I don't want to force the user to enclose input in " for string, the most common input (and the only one today ;-))

Another option is to use something as follows: 
- introduce `value` field
- use types as defined in a yaml file (i.e. use boolean true if it is written without quotes)
- add special key with suffix `__input` into context
- add implicit `value: "{{{<name>__input}}}"`

This approach would allow to assign value as a function of user input. It would be possible to express something like this:
```
  - name: license_text
    ask: Enter URL of a license
    value: {{http_get license_text__input}}
```

**Comment by davidB** [comment]
👍 Yes it could become a useful features.

As side-note for license you can do:
```yaml
variables:
  - name: licenses_json
    default_value: '{{ http_get "https://spdx.org/licenses/licenses.json" }}'
    hidden: true
  - name: license_id
    default_value: "Apache-2.0"
    ask: select a license
    select_in_values: '{{ json_str_query "licenses[? !isDeprecatedLicenseId].licenseId" licenses_json }}'
```

Or simpler,  import the template oss_license (like in this extract from https://github.com/davidB/amethyst-starter-2d/blob/variant/ffizer/ )
```yaml
imports:
  - uri: "git@github.com:ffizer/templates_default.git"
    rev: "master"
    subfolder: "oss_license"
```
