### ISSUE TITLE
[Feature] Run commands after scaffold completion

### ISSUE THREAD

**Issue by iilyak** [ffizer/ffizer#188]
Usually when new project is started there is a need to run some initialization commands, such as for example:
- git init
- git remote add upstream ....
- git worktree add --track -b gh-pages site origin/gh-pages
- direnv allow

It would be nice to be able to run the commands automatically or be able to print them (and suppress all other output) to pipe into sh. 
I.e. the scaffold command would look like `ffizer apply --source <source_dir> --destination <dest_dir> | sh`.

**Comment by davidB** [comment]
It's a feature on my TODO list since the start. I never work on it due to priority and some issues & questions (your point of view is welcome):

- for security (not run arbitrary command on the user's host): for each command, the user is asked "do you want to run .... [Y/n] ?"
- in case of composed template (with imports), what is the right order to apply command (depth-first or breadth-first or ???)
- common question for scripting commands (see [Commands, Scripts and Sub Tasks](https://sagiegurari.github.io/cargo-make/#usage-task-command-script-task) from cargo-make doc):
  - how to manage multi-OS support (linux, macos x, windows)
  - how to handle error
  - what is the syntax (a string, an array, ...)

The first/next step that I plan is to allow template to include a notice messages to display at the end of the generation. This message could include command and ask user to copy/paste them.

WDYT ?

**Comment by iilyak** [comment]
> for security (not run arbitrary command on the user's host): for each command, the user is asked "do you want to run .... [Y/n] ?"

👍 

> in case of composed template (with imports), what is the right order to apply command (depth-first or breadth-first or ???)

maybe do a topological sorting of the nodes? However there might be the cases when user might want to override the order.

> common question for scripting commands (see Commands, Scripts and Sub Tasks from cargo-make doc): 

* Q: how to manage multi-OS support (linux, macos x, windows)
  * A: I don't know a good way to abstract OS specifics for arbitrary commands. I think this is out of scope of ffizer. There are some projects which attempt doing it (without much success IMO):
    * https://github.com/sagiegurari/duckscript
    * https://github.com/mesalock-linux/mesabox
    * https://github.com/uutils/coreutils
    * https://github.com/oconnor663/duct.rs (not directly related but interesting)
    * https://github.com/isurfer21/UniversalShell (not in rust)
    * https://github.com/nushell/nushell (possibly unrelated)
* Q: how to handle error
  * A: I don't think it is possible to rollback side effects of the arbitrary commands (if it is what you mean in the question). Can you elaborate on this a bit?
* Q: what is the syntax (a string, an array, ...)
  * A: Maybe something like the following:
```
variables:
     - name: github_org
       ask: Github organization or user name
     - name: repo_name
        ask: Repository name 

imports:
  - uri: "git@github.com:ffizer/templates_default.git"
    id: base
    rev: "master"
    subfolder: "gitignore_io"
  - uri: "git@github.com:myown/docs-template.git"
    id: docs
    rev: "master"
    subfolder: "docs"

commands:
    - id: postscaffold
       command: |
           git init
           git remote add upstream git@github.com:{{github_org}}/{{repo_name}}.git
           git worktree add --track -b gh-pages site origin/gh-pages
       order:
          - base # we want `postscaffold` commands from ffizer/templates_default.git to run before ours
          - self # this is how we refer to `postscaffold` command in the current `.ffizer.yaml`
          - docs
```

To somewhat abstract OS differences one could write something like
```
commands:
    - id: postscaffold
       windows: 
           command: |
               ...
       posix:
          command: |
               ...
       darwin:
          command: |
               ...
```

OR (easier to implement but might be not a good choice long term)
```
commands:
   id: postscaffold
   command: |
       {{#if (eq  platform "darwin") ~}}
        ....
       {{~/if}}
       {{#if (eq  platform "windows") ~}}
        ....
       {{~/if}}
```
