### ISSUE TITLE
add description to template's variable

### ISSUE THREAD

**Issue by AlbanMinassian** [ffizer/ffizer#29]
Quand on lance ``ffizer apply`` il manque une petite description des variables.
Peut être permettre une nouvelle variable du genre

```
variables:
  - name: project
    default_value: my-project
    description: a long description ...
```

Cordiallement
Alban

**Comment by davidB** [comment]
Oui, il faut que je documente et ameliore cette partie. Car cela exist, mais avec un autre nom:
```
variables:
  - name: project
    default_value: my-project
    ask: what is the value for `project`
```
