### ISSUE TITLE
error with composed repositories

### ISSUE THREAD

**Issue by iilyak** [ffizer/ffizer#409]
The following `.ffizer.yaml` produces following error
```
variables:
  - name: author_name
    default_value: '{{ env_var "USERNAME" }}'

ignores:
  - .git # exclude .git of the template host

imports:
  - uri: "https://github.com/ffizer/templates_default.git"
    rev: "master"
    subfolder: "oss_license"
```

```
ffizer test-samples --source .
Jul 15 11:58:36.085 ERROR ffizer: cmd: CliOpts {
    verbose: 0,
    cmd: TestSamples(
        TestSamplesOpts {
            src: SourceLoc {
                uri: SourceUri {
                    raw: ".",
                    path: ".",
                    host: None,
                },
                rev: "master",
                subfolder: None,
            },
            offline: false,
        },
    ),
}
Jul 15 11:58:36.086 ERROR ffizer: failed: SerdeYaml {
    source: Scan(
        ScanError {
            mark: Marker {
                index: 30,
                line: 1,
                col: 30,
            },
            info: "while scanning a tag, did not find expected whitespace or line break",
        },
    ),
}
```

If I comment out imports it works fine.

The error message is very cryptic and it is hard to guess that is caused by `imports` section.
