### ISSUE TITLE
add to how-to

### ISSUE THREAD

**Issue by davidB** [ffizer/ffizer#651]
- How to convert a variable after set by user ?
  tips use and intermediate value.

    ```yaml
    - name: v1_input
      ask: "v1"
    - name: v1
      default_value: "{{ to_lower v1_input }}"
      hidden: true
    ```
